django1/django1/basic_app/urls.py
from django.conf.urls import url
from django.urls.resolvers import URLPattern
from django.urls import path

from basic_app import views

app_name = 'basic_app'

urlpatterns=[
    path('register/', views.register, name='register'),
    

]

django1/django1/django1/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('/', views.index, name='index'),
    path('basic_app/', include('basic_app.urls')),


]

django1/django1/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)

    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to = 'profile_pics', blank = True)

    def __str__(self):
        return self.user.username

django1/django1/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserInfoForm(forms.ModelForm):
    class Meta:
        model= UserInfo
        fields = ('portfolio_site', 'profile_pic')

django1/django1/basic_app/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from .models import UserInfo
from .forms import UserForm, UserInfoForm

# Create your views here.
def index(request):
    return render(request,'basic_app/index.html')

django1/django1/basic_app/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <title> </title>
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
                <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                <li><a class="navbar-link" href="{% url 'basic_app:register' %}">Register</a></li>

            </ul>
        </div>
    </nav>

    {% block body_block %}
    {% endblock %}    
</body>
</html>

django1/django1/basic_app/templates/basic_app/index.html
{% extends "basic_app/base.html" %}
{% block body_block %}

<div class="jumbotron">
    <h1>Welcome to index page</h1>
</div>

{% endblock %}

django1/django1/basic_app/templates/basic_app/registration.html
{% extends "basic_app/base.html" %}
{% load staticfiles %}
{% block body_block %}

<div class="jumbotron">
    {% if  registered %}
        <h1> Thankyou</h1>
    {% else %}
    <h1> Register here!</h1>
    <h3> Fill out the form:</h3>

    <form method="POST" enctype="multipart/form-data" >
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" name="" value="Register">
    </form>


    {% endif %}
</div>


{% endblock %}